<Project Sdk="Microsoft.NET.Sdk">
    <!--<Import Project="..\..\common.props" />-->

    <PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
        <AssemblyTitle>Akka.Persistence.FSharp</AssemblyTitle>
        <Description>F# API for persistence actors in Akka.NET</Description>
        
        <PackageTags>akka;actors;actor model;Akka;concurrency;F#;Fsharp;persistence;eventsource</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<EnablePackageValidation>true</EnablePackageValidation>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<OutputPath>./bin</OutputPath>
		<IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>
		<IsOSX Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'">true</IsOSX>
		<IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>

		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Authors />
		<Description />
    </PropertyGroup>

    <ItemGroup />

    <ItemGroup>
        <Compile Include="FsApi.fs" />
        <!--<Content Include="LICENSE.txt" />-->
        <None Include="PostBuildEvent.Linux.ps1" />
        <None Include="PostBuildEvent.ps1" />
        <None Include="README.md" />
    </ItemGroup>


    <!--<ItemGroup>
        <ProjectReference Include="..\Akka.FSharp\Akka.FSharp.fsproj" />
        <ProjectReference Include="..\Akka.Persistence\Akka.Persistence.csproj" />
    </ItemGroup>-->




	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
    </PropertyGroup>


	<PropertyGroup>
		<PackageId>FAkka.$(AssemblyName)</PackageId>
		<!--<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>-->
		<Version>1.5.62</Version>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" />
		<PackageReference Include="FAkka.Akka.FSharp" Version="1.5.62" />
		<PackageReference Include="Akka.Persistence" Version="1.5.62" />
		<PackageReference Include="FSharp.Core" Version="10.0.105" />
		<PackageReference Include="FSharp.Quotations.Evaluator" Version="2.1.0" />
	</ItemGroup>

	<ItemGroup>
	</ItemGroup>

	<PropertyGroup Condition="'$(IsWindows)'=='true'">
		<DefineConstants>Windows</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(IsOSX)'=='true'">
		<DefineConstants>OSX</DefineConstants>
	</PropertyGroup>
</Project>