<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Authors>Bartosz Sypytkowski and contributors</Authors>
        <Copyright>Bartosz Sypytkowski and contributors</Copyright>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/Horusiath/Akkling</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <RepositoryUrl>https://github.com/Horusiath/Akkling</RepositoryUrl>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Version>1.569.101.301</Version>
        <PackageId>FAkka.$(AssemblyName)</PackageId>
    </PropertyGroup>
    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="\"/>
        <Compile Include="AssemblyInfo.fs" />
    </ItemGroup>
</Project>
