<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>F# wrapper library for Akka.NET with persistence support. Optimized for FAkka.</Description>
    <PackageTags>akka.net fsharp akkling persistence eventsourcing</PackageTags>
          <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
          <PackageReadmeFile>README.md</PackageReadmeFile>
          <Authors />
          <Description />
  </PropertyGroup>
        <PropertyGroup>
                <PackageId>FAkka.$(AssemblyName)</PackageId>
        </PropertyGroup>
  <ItemGroup>
    <None Include="PostBuildEvent.ps1" />
    <Compile Include="PersistentActor.fs" />
    <Compile Include="AtLeastOnceDelivery.fs" />
    <Compile Include="Patterns.fs" />
    <Compile Include="Spawning.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Akka" Version="1.5.69" />
    <PackageReference Include="FAkka.Akkling" Version="1.569.101.301" />
    <PackageReference Include="FAkka.Akkling.Streams" Version="1.569.101.301" />
    <PackageReference Include="Akka.Persistence" Version="1.5.69" />
    <PackageReference Update="FSharp.Core" Version="10.1.301" />
  </ItemGroup>

  <Target Name="PostPackNugetDeploy" AfterTargets="Pack" Condition="'$(Configuration)' == 'Release'">
    <Exec Command="powershell ./PostBuildEvent.ps1 FAkka.$(AssemblyName)" />
  </Target>
</Project>
