<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>F# wrapper library for Akka.NET with reactive streams support. Optimized for FAkka.</Description>
    <PackageTags>akka.net fsharp akkling reactive streams</PackageTags>
          <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
          <PackageReadmeFile>README.md</PackageReadmeFile>
          <Authors />
          <Description />
  </PropertyGroup>
  <ItemGroup>
    <None Include="PostBuildEvent.ps1" />
    <Compile Include="Framing.fs" />
    <Compile Include="Prolog.fs" />
    <Compile Include="Stages.fs" />
    <Compile Include="Sink.fs" />
    <Compile Include="SubFlow.fs" />
    <Compile Include="BidiFlow.fs" />
    <Compile Include="Graph.fs" />
    <Compile Include="Flow.fs" />
    <Compile Include="KillSwitch.fs" />
    <Compile Include="Source.fs" />
    <Compile Include="WithContext.fs" />
    <Compile Include="Tcp.fs" />
  </ItemGroup>
        <PropertyGroup>
                <PackageId>FAkka.$(AssemblyName)</PackageId>
        </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Akka" Version="1.5.69" />
    <PackageReference Include="FAkka.Akkling" Version="1.569.101.301" />
    <PackageReference Include="Akka.Streams" Version="1.5.69" />
    <PackageReference Update="FSharp.Core" Version="10.1.301" />
  </ItemGroup>

  <!-- 統一呼叫跨平台腳本 -->
  <Target Name="PostPackNugetDeploy" AfterTargets="Pack" Condition="'$(Configuration)' == 'Release'">
    <Exec Command="powershell ./PostBuildEvent.ps1 FAkka.$(AssemblyName)" />
  </Target>
</Project>
