<Project Sdk="Microsoft.NET.Sdk">
    <!--<Import Project="..\..\common.props" />-->

    <PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
        <AssemblyTitle>Akka.FSharp</AssemblyTitle>
        <Description>F# API support for Akka.NET</Description>
        
        <PackageTags>$(AkkaPackageTags);F#;fsharp</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<EnablePackageValidation>true</EnablePackageValidation>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<OutputPath>./bin</OutputPath>
		<IsWindows Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))' == 'true'">true</IsWindows>
		<IsOSX Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'">true</IsOSX>
		<IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>

		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Authors />
		<Description />
		<PackageId>FAkka.$(AssemblyName)</PackageId>
		<Version>1.5.69</Version>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" />
        <!--<Content Include="LICENSE.txt" />-->
        <None Include="PostBuildEvent.Linux.ps1" />
        <None Include="PostBuildEvent.ps1" />
        <Compile Include="FsApi.fs" />
        <Compile Include="Schedulers.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Akka.Cluster.Sharding" Version="1.5.69" />
        <PackageReference Include="FSharp.Quotations.Evaluator" Version="2.1.0" />
        <!--<PackageReference Include="FsPickler" Version="5.3.2" />-->
		<PackageReference Include="FAkka.FsPickler" Version="10.1.301" />
		<PackageReference Include="Akka" Version="1.5.69" />
        <PackageReference Update="FSharp.Core" Version="10.1.301" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
    </PropertyGroup>

	<PropertyGroup>
		<!--<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>-->
	</PropertyGroup>



	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" />
	</ItemGroup>
	<ItemGroup>

		<!--<None Include="LICENSE.txt" Pack="true" PackagePath="" />-->
	</ItemGroup>



	<PropertyGroup Condition="'$(IsWindows)'=='true'">
		<DefineConstants>Windows</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(IsOSX)'=='true'">
		<DefineConstants>OSX</DefineConstants>
	</PropertyGroup>


	<Target Name="PostPackNugetDeployWindows" AfterTargets="Pack" Condition="'$(Configuration)' == 'Release'">
		<Exec Command="powershell -c &quot;write-host '====== Start Post-Build Event ======'&quot;&#xD;&#xA;powershell ./PostBuildEvent.ps1 FAkka.$(AssemblyName)" />
	</Target>
</Project>