// <auto-generated>
//     Generated by the FSharp WriteCodeFragment class.
// </auto-generated>
namespace FSharp

open System
open System.Reflection


[<assembly: System.Reflection.AssemblyCompanyAttribute("Akka.FSharp")>]
[<assembly: System.Reflection.AssemblyConfigurationAttribute("Release")>]
[<assembly: System.Reflection.AssemblyCopyrightAttribute("Bartosz Sypytkowski and contributors")>]
[<assembly: System.Reflection.AssemblyFileVersionAttribute("1.5.0.0")>]
[<assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.5.0+b773fd94309c9db6f8e94f103ab84358c107c363")>]
[<assembly: System.Reflection.AssemblyProductAttribute("Akka.FSharp")>]
[<assembly: System.Reflection.AssemblyTitleAttribute("Akka.FSharp")>]
[<assembly: System.Reflection.AssemblyVersionAttribute("1.5.0.0")>]
[<assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/Horusiath/Akkling")>]
do()
