<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>F# wrapper library for Akka.NET cluster sharding module. Optimized for FAkka.</Description>
    <PackageTags>akka.net fsharp akkling cluster sharding</PackageTags>
          <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
          <PackageReadmeFile>README.md</PackageReadmeFile>
          <Authors />
          <Description />
  </PropertyGroup>

  <ItemGroup>
    <None Include="PostBuildEvent.ps1" />
    <Compile Include="ClusterExtensions.fs" />
    <Compile Include="ClusterSingleton.fs" />
    <Compile Include="DistributedPubSub.fs" />
    <Compile Include="ClusterClient.fs" />
    <Compile Include="EntityRef.fs" />
    <Compile Include="ClusterSharding.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Akka" Version="1.5.69" />
    <PackageReference Include="FAkka.Akkling" Version="1.569.101.301" />
    <PackageReference Include="FAkka.Akkling.DistributedData" Version="1.569.101.301" />
    <PackageReference Include="FAkka.Akkling.Persistence" Version="1.569.101.301" />
    <PackageReference Include="Akka.Cluster.Sharding" Version="1.5.69" />
    <PackageReference Update="FSharp.Core" Version="10.1.301" />
  </ItemGroup>

        <PropertyGroup>
                <PackageId>FAkka.$(AssemblyName)</PackageId>
        </PropertyGroup>
  <Target Name="PostPackNugetDeploy" AfterTargets="Pack" Condition="'$(Configuration)' == 'Release'">
    <Exec Command="powershell ./PostBuildEvent.ps1 FAkka.$(AssemblyName)" />
  </Target>
</Project>
