<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyTitle>Akka.Persistence.SqlServer</AssemblyTitle>
        <Description>Akka.Persistence support for SQL Server.
        </Description>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<OutputPath>./bin</OutputPath>
		<Authors />
		<Description />
    </PropertyGroup>
    <ItemGroup>
      <None Remove="icon.png" />
    </ItemGroup>
	<ItemGroup>
		<None Include="icon.png" Pack="true" PackagePath="" />
	</ItemGroup>

	<PropertyGroup>
		<PackageId>FAkka.$(AssemblyName)</PackageId>
		<Version>1.5.57</Version>
	</PropertyGroup>
    <ItemGroup>
        <Content Include="icon.png" />
        <EmbeddedResource Include="sql-server.conf" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Akka.Persistence.Sql.Common" Version="1.5.39" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0-preview3.25342.7" />
    </ItemGroup>
	<Target Name="PostPackNugetDeployWindows" AfterTargets="Pack" Condition="'$(Configuration)' == 'Release'">
		<Exec Command="powershell -c &quot;write-host '====== Start Post-Build Event ======'&quot;&#xD;&#xA;powershell .\PostBuildEvent.ps1 FAkka.$(AssemblyName)" />
	</Target>

</Project>