<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyTitle>Akka.Persistence.SqlServer</AssemblyTitle>
        <Description>Akka.Persistence support for SQL Server.
        </Description>
        <TargetFramework>net9.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
    <ItemGroup>
      <None Remove="icon.png" />
    </ItemGroup>
	<ItemGroup>
		<None Include="icon.png" Pack="true" PackagePath="" />
	</ItemGroup>

	<PropertyGroup>
		<PackageId>FAkka.$(AssemblyName)</PackageId>
		<Version>1.5.30</Version>
	</PropertyGroup>
    <ItemGroup>
        <Content Include="icon.png" />
        <EmbeddedResource Include="sql-server.conf" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Akka.Persistence.Sql.Common" Version="1.5.30" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.0-preview2.24304.8" />
    </ItemGroup>
</Project>