<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Library used for working with Akka.NET using F# in type safe manner. Optimized for FAkka.</Description>
    <PackageTags>akka.net fsharp akkling</PackageTags>
          <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
          <PackageReadmeFile>README.md</PackageReadmeFile>
          <Authors />
          <Description />
  </PropertyGroup>
  <ItemGroup>
    <None Include="PostBuildEvent.ps1" />
    <Compile Include="Atomics.fs" />
    <Compile Include="ActorRefs.fs" />
    <Compile Include="Actors.fs" />
    <Compile Include="MessagePatterns.fs" />
    <Compile Include="ActorBuilder.fs" />
    <Compile Include="FaultHandling.fs" />
    <Compile Include="Props.fs" />
    <Compile Include="Configuration.fs" />
    <Compile Include="Spawning.fs" />
    <Compile Include="Behaviors.fs" />
    <Compile Include="Schedulers.fs" />
    <Compile Include="Logging.fs" />
    <Compile Include="Utils.fs" />
    <Compile Include="Extensions.fs" />
    <Compile Include="IO.fs" />
  </ItemGroup>
        <PropertyGroup>
                <PackageId>FAkka.$(AssemblyName)</PackageId>
        </PropertyGroup>
        <ItemGroup />
  <ItemGroup>
    <PackageReference Include="Akka" Version="1.5.69" />
    <PackageReference Include="Akka.Serialization.Hyperion" Version="1.5.69" />
    <PackageReference Update="FSharp.Core" Version="10.1.301" />
  </ItemGroup>

  <!-- 統一呼叫跨平台腳本 -->
  <Target Name="PostPackNugetDeploy" AfterTargets="Pack" Condition="'$(Configuration)' == 'Release'">
    <Exec Command="powershell ./PostBuildEvent.ps1 FAkka.$(AssemblyName)" />
  </Target>
</Project>
