<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>F# wrapper library for Akka.NET Streams TestKit library. Optimized for FAkka.</Description>
    <PackageTags>akka.net fsharp akkling reactive streams testing fscheck</PackageTags>
          <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
          <PackageReadmeFile>README.md</PackageReadmeFile>
          <Authors />
          <Description />
  </PropertyGroup>
  <ItemGroup>
    <None Include="PostBuildEvent.ps1" />
    <Compile Include="Library.fs" />
  </ItemGroup>
  <ItemGroup />
  <ItemGroup>
    <PackageReference Include="FAkka.Akkling" Version="1.562.10.103-dgx.1" />
    <PackageReference Include="FAkka.Akkling.TestKit" Version="1.562.10.103-dgx.1" />
    <PackageReference Include="Akka.Streams.TestKit" Version="1.5.62" />
    <PackageReference Update="FSharp.Core" Version="10.0.103" />
  </ItemGroup>
        <PropertyGroup>
                <PackageId>FAkka.$(AssemblyName)</PackageId>
        </PropertyGroup>
  <Target Name="PostPackNugetDeploy" AfterTargets="Pack" Condition="'$(Configuration)' == 'Release'">
    <Exec Command="powershell ./PostBuildEvent.ps1 FAkka.$(AssemblyName)" />
  </Target>
</Project>
